version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: weather_db
    environment:
      - POSTGRES_DB=meteo_db
      - POSTGRES_USER=elcapo
      - POSTGRES_PASSWORD=elcapo
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - weather-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U elcapo -d meteo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: weather_web
    environment:
      - DATABASE_URL=postgresql://elcapo:elcapo@db:5432/meteo_db
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - weather-network
    volumes:
      - ./app:/app

volumes:
  postgres_data:

networks:
  weather-network:
    driver: bridge